### ISSUE TITLE
[JOSS Review] Software Paper Checklist

### ISSUE THREAD

**Issue by praneethd7** [EleutherAI/ccs#15]
A couple of suggestions for the paper:

- [ ] Currently the methodology is described within the `Statement of need`. I would recommend creating a section of its own called `Methodology` or `Implementation`
- [ ] A real-world example in the `Statement of need` section would be helpful. You could re-use the same example within the documentation here on GitHub
- [ ] Describe related works and alternative packages (if any) in the `State of the field`. Mention how your tool is different and describe comparative advantages
> - [ ] State of the field: Do the authors describe how this software compares to other commonly-used packages? 
### Minor
- [ ] There are some missing citations in the paper
- [ ] The `References` section header is missing
- [ ] Mentioning about discord server in the Abstract seems redundant

Cross Reference: https://github.com/openjournals/joss-reviews/issues/6511

**Comment by praneethd7** [comment]
Satisfied with the changes.
